from sqlalchemy import create_engine
from sqlalchemy.schema import CreateTable
from app.models import Base

engine = create_engine('postgresql://')
with open('migration_content.py', 'w') as f:
    f.write("def upgrade() -> None:\n")
    for table in Base.metadata.sorted_tables:
        f.write("    # ### commands auto generated by Alembic - please adjust! ###\n")
        f.write("    pass\n")

print("DDL script created")
